{% set version = "0.0.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-drr
  version: {{ version|replace("-", "_") }}

source:
  fn: DRR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/DRR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DRR/DRR_{{ version }}.tar.gz
  sha256: 93e365a4907e301ae01f7d943e6bdcda71ef23c51a4759ba3c94bcf842d4e0f8

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-cvst
    - r-matrix
    - r-kernlab
  run:
    - r-base
    - r-cvst
    - r-matrix
    - r-kernlab

test:
  commands:
    - $R -e "library('DRR')"           # [not win]
    - "\"%R%\" -e \"library('DRR')\""  # [win]

about:
  home: https://github.com/gdkrmr/DRR
  license: GPL-3
  summary: An Implementation of Dimensionality Reduction via Regression using Kernel Ridge Regression.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
