travis:
  secure:
    BINSTAR_TOKEN: OJGiZodApRYxDbGN1xEU9ewfDPXrhVxKhXoG10AIKHMHVDb71W0PekgXA8fl1nN3xW+3zilI0XVSEqQwK393EGTkqmJjZXxd+5pnlNXQyBzSIcsgG58eC0gkcK0F2ymNcWft4C6ZM25YuVlBAuRJVVpJejR9Jkln+VKPE4xencQCQIorBNFbzkAfuuYlNTr0+fK09pzASYzzwt86e1KRBDBPW5kd3W2v/Svu/qYaePobDoufDLsNH4Bwdx7QhJ2sSJVOhGI55rf8BYJJR7/5gyUyPsZWmIsi7PO1KJp4idO4pva3eXRRc5IdcmqOBAlBHxR7zaytCEsd8u5OcF/Y4WEjWvF7303E8jyBdMinU8pL2BCaS2lOBBY1pXJmVXay0P0Dd8jzGRn00Cqb6+aJXbZ8I6fGhtAWO6/OCY4vgJ9dB1xUB7abDf4OnHsGc9K8Z3MszOWebU94kQM6hVIlcl0shezXLP6Ks9HPsXtR2dr9b+ljDngUL+D/ZLBIHqhz7U3MnVpbv4I8VeGBQo1m6zTkDuTCYfOEBnxd+3hJQyuVySrrSF653nhiryhdrl1qllePOyHGEPE26Lt9BC5J3mP5NG+bB1Xb1q+iwzU7YOoku+4vD7vJP5gtxDqoeNDCCWy+p9Iw8rAdtWbC5dyoY/6p9U5KlxrcCwW9xPN1F8k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
