travis:
  secure:
    BINSTAR_TOKEN: CagVZOLFEI5MEoK5ZMDptbX0HgOM30CnFVuVJs8qIWoBEjh2jXlUwqH77f5eU1ltRLBOyB2xs5vvH8unYmCO027m7ToEVYRriw2Nr4iRck1qpLZI8b+mWUs5UFCkNtWfIZQDSahXWREVabqi1GR9D5lmAZ9c3MQlZFkCce3kv/gDf7LaIb0AYEvERNwfdBYsPvNveih979jcY5ApqDVLjofX808bRkQmk6DQCyMOoBs8AfBAwWB5vQQdeD8ln1rUuWnG3btAUteXh/kpOVLsuM6+8t6MrCXWu3uGFg2Tilkl38hhTODwYId1OiyUSYBeiNXvig3wZKOZc/pENWYAOv749UkWqNXV9bseMuQt/9TEBN5uHQqF+RsAapNIxKaSXZu9VuVJ8ao4FMf4miAgnzIaXhIUplI0vRKGdMcobpWPmpCFFndJN6KdTYbRAMgAtV9MkK+oKkpE90dtTMD6PxxQxMmrv8tHJKPVakMBknFtpNaNVYO7U904eemDQCWAxfU439EvUQgNYZbP4oNHy/7j1AIgpGntG2Bd9PRt0xqfJ2RICO6MeUl5f8CDsts+3LBWdMXRjxq5HgXcWcYYQxFk0iEbjtZIpcevOFwGOXtYxv+te1TAiaq5Lshoy5RLgmCO+i/wiERPtRJ4bFyTpFEwf7bCxFRVKdArEx79ZQM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
