travis:
  secure:
    BINSTAR_TOKEN: R3kZA2TE0NkYN5Ufg6qe7yl0x7qrgDqakAdWv/iufjJmEGYohKoCz7SzSoWyL8bmsyhVO/6+gNfFajfalGByM97y7oLiaOjKlCx4y9vrPygpQ/70/3Rfvan725mw7ev22ebVD/4slMJCzLHD5BnGd45zWJGbuq4v9U3ajdHE4PbhI04+GbmG9Dm3oFhRRtIAwqPpevJY5XM5GnzjMEwEsyd3xejTIf5ZiARsSbwW20gu0+u/4ALWTHYOMCgkCIe3A70IhDR1je/A485EFW+izUs61zhTADaKPTx0HH0qk2NHTB69M+FSctxFewB5OunCwWY5NRCn6nD68GTSZ+JijSVV4fYoPc0WqFBABIuJPzNeENKcHl4i4LYUlD26iLnmo4Pa36IxpU2f3W9Ee/SnaleQ4Z70vENFs4BvtUmLIEcE0AhyU6Lg2Vqk4RfgTPkJVfBL7SK66klxOc4Z5oIBZMiOwg+gnzyk5Nxfe5IljswBqFo5mB/NATeFytvGR0Imhofp1qdNZNab2YcwD6DAFtnwJl9Bmz7PMyLc9ocpz9zQlI3ySBSw0HiOJno8FwqEgNvxW1E2Hab8AzfjEzL94MRw0aKHLDL8LacsaQDtVsEvjoKnef/XxFISG0/F+RLD4/sLSPwdhB81wTKeL2o+OCVS0LsVf9Fvi2jMfV60ccs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
